# Generated by Django 2.2.12 on 2021-07-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0003_auto_20210726_0129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together=set(),
        ),
    ]
