# Generated by Django 2.2.12 on 2021-07-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0006_auto_20210726_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set(),
        ),
    ]
