# Generated by Django 2.2.12 on 2021-07-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0010_auto_20210727_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Thread',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thread', models.ForeignKey(db_column='Thread', on_delete=django.db.models.deletion.DO_NOTHING, to='Task1.Tweet')),
                ('Tweet', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Tweet', to='Task1.Tweet')),
            ],
            options={
                'unique_together': {('Thread', 'Tweet')},
            },
        ),
    ]
