# Generated by Django 2.2.12 on 2021-07-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0011_auto_20210727_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='Thread',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
