# Generated by Django 2.2.12 on 2021-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0012_auto_20210727_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Task1.Thread')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Task1.Tweet')),
            ],
        ),
    ]
