# Generated by Django 2.2.12 on 2021-07-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0016_threadtweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
