# Generated by Django 2.2.12 on 2021-07-29 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task1', '0017_auto_20210727_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
